using static SDL2.SDL;

namespace SDL2.NET.HintTypes;

/// <summary>
/// A hint that specifies whether controllers used with the Apple TV generate UI events. <see cref="SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS" href="https://wiki.libsdl.org/SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS"/>
/// </summary>
/// <remarks>
/// When UI events are generated by controller input, the app will be backgrounded when the Apple TV remote's menu button is pressed, and when the pause or B buttons on gamepads are pressed.
/// </remarks>
public sealed class AppleTVControllerUIEvents : BinaryHint
{
    internal AppleTVControllerUIEvents() : base(SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS) { }
}
